apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    name: proxy
spec:
  ports:
  - name: proxy-http
    port: 80
    targetPort: proxy-http
    protocol: TCP
  - name: proxy-https
    port: 443
    targetPort: proxy-https
    protocol: TCP
  selector:
    name: proxy