apiVersion: v1
kind: ReplicationController
metadata:
  name: site-one
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: site-one
    spec:
      containers:
      - name: site-one
        image: site-one-container
        ports:
        - containerPort: 80
          name: site-one-http
