apiVersion: v1
kind: ReplicationController
metadata:
  name: site-two
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: site-two
    spec:
      containers:
      - name: site-two
        image: site-two-container
        ports:
        - containerPort: 80
        name: site-two-http
